### ISSUE TITLE
Can't import  gltf file 

### ISSUE THREAD

**Issue by happydpc** [bazhenovc/malwerks#1]
Test sponza.gltf. 

```rust
thread 'main' panicked at 'failed to open buffer file: Os { code: 206, kind: Other, message: "Filename or extension is too long" }', malwerks_tools\src\gltf_meshes.rs:44:63
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/30f0a07684f6c1f5df62d69e9519d82e13d6bf2d\/library\std\src\panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/30f0a07684f6c1f5df62d69e9519d82e13d6bf2d\/library\core\src\panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/30f0a07684f6c1f5df62d69e9519d82e13d6bf2d\/library\core\src\option.rs:1221
   3: core::result::Result<std::fs::File, std::io::error::Error>::expect<std::fs::File,std::io::error::Error>
             at C:\Users\Administrator\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\result.rs:965
   4: import_gltf::gltf_meshes::import_meshes
             at .\malwerks_tools\src\gltf_meshes.rs:44
   5: import_gltf::import_gltf
             at .\malwerks_tools\src\import_gltf.rs:71
   6: import_gltf::main
             at .\malwerks_tools\src\import_gltf.rs:99

```

Test Lantern.gltf.
C:\malwerks\target\debug>import_gltf.exe  --input Lantern.gltf
[malwerks_tools\src/import_gltf.rs:68] &base_path = ""
[malwerks_tools\src\gltf_meshes.rs:43] &file_path = "Lantern.bin"
thread 'main' panicked at 'failed to get image file metadata: Os { code: 3, kind: NotFound, message: "
The system could not find the specified path." }', malwerks_tools\src\texconv.rs:29:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

This is the test file.
[KhronosGroup glTF-Sample-Models master 2.0-Lantern_glTF.zip](https://github.com/bazhenovc/malwerks/files/5144790/KhronosGroup.glTF-Sample-Models.master.2.0-Lantern_glTF.zip)

**Comment by bazhenovc** [comment]
Hi,

This currently requires a few extra steps, I'll write some documentation on this today.

**Comment by bazhenovc** [comment]
@happydpc

Here you go: https://github.com/bazhenovc/malwerks/wiki/Pre-alpha:-how-to-import-GLTF-files-and-how-to-run-the-playground

The whole process is extremely clunky right now since this is in very early stages of development, I'll work on improving the workflow in the future.

**Comment by happydpc** [comment]
> @happydpc
> 
> Here you go: [bazhenovc/malwerks/wiki/Pre-alpha:-how-to-import-GLTF-files-and-how-to-run-the-playground](https://github.com/bazhenovc/malwerks/wiki/Pre-alpha:-how-to-import-GLTF-files-and-how-to-run-the-playground)
> 
> The whole process is extremely clunky right now since this is in very early stages of development, I'll work on improving the workflow in the future.

Thank you. I am going to have a try.
