### ISSUE TITLE
Bench the cluster culling

### ISSUE THREAD

**Issue by happydpc** [bazhenovc/malwerks#2]
I want to test the cluster culling, but there's no such test case for this.

**Comment by bazhenovc** [comment]
Hi,

Cluster culling is enabled by default and there's debug UI to toggle it on and off, once I write some documentation on how to actually run it you'll be able to test it.

**Comment by bazhenovc** [comment]
@happydpc I've added some documentation to the main README file, hope that helps with understanding what's going on under the hood.
